### ISSUE TITLE
why must I be forced to delete the oldest batch?

### ISSUE THREAD

**Issue by Username23453** [Myzel394/Alibi#76]
I'm okay with it segmenting videos in batches & having no choice but to do this. But why must I be forced to delete the oldest batch?
 Also, I suppose I could choose the minimum choice of 10 second batches, which means it would only delete the first 10 seconds of recording. But why must I be forced to do this?
 
 -Thanks.
 
 Also, I just want to say thanks for creating this program, its the only video/audio recording that works when running in the background. I'm impressed.

**Comment by Myzel394** [comment]
I'm sorry, but I'm not sure what you mean.

Alibi deletes the old batches to avoid the device running out of storage and to only store the minimum required amount of data. If you want to store, let's say, the last 60 minutes once you press on save, Alibi makes sure that only the last 60 minutes of footage are stored on your device at any given time.

**Comment by Myzel394** [comment]
I'm sorry but this is not supported. If you want to continuously record in the background, you'll need to use a different recorder app. Alternatively you could also set Alibi's recording time very high.

**Comment by Myzel394** [comment]
> you must delete & lose the first 10 seconds? this is forced? Its not that big of a deal i guess

I think there's still a misunderstanding here.

When you start recording with Alibi, it will immediately start recording in the background. Every few seconds / minutes Alibi will shortly interrupt the recording to save it and start a new one. The batch size is the value that controls when to interrupt. When the max amount of recording time is reached, Alibi will delete its old recordings.

So, if you set a batch size of 10 seconds and a max time of 10 minutes for example, Alibi will start recording a bunch of 10-seconds long videos. Every 10 seconds, a new recording will be started. Once you've recorded with Alibi for 10 minutes, Alibi will delete the oldest 10-second recording batch.

> I guess one can look at it as that the app has a 10 second delay until it starts to actually save the recording & never delete it.

Alibi immediately* starts to record as soon as you press on start recording. I'm still not sure what you mean by "never delete it".

I hope it's more clear now how Alibi works. If you still got questions, feel free to ask them! :)

\* Almost immediately, when you want to open the camera on Android (to access it), there's a small delay (about a few seconds) until the camera is ready to use. But this is out of my control and shouldn't be a big deal since all apps are affected by this and it's only such a short time.

**Comment by Myzel394** [comment]
>  In reality, there is only one batch that continually rewrites over itself when its duration ends? it recycles itself

You almost got it! :D It's not one batch that rewrites itself, but Alibi creates multiple batches. So given my above example with a 10 second batch and 10 minute time limit, you will start with one batch, then two batches, three batches, four batches ... until you got 60 batches. So 60 * 10 seconds = 600 seconds = 10 minutes; the first batch will then be deleted.

Internally, Alibi gives each batch an increasing number, so it'll save them like this:

Within the first 10 minutes:
* `alibi_batch_1.mp4`
* `alibi_batch_2.mp4`
* `alibi_batch_3.mp4`
* ...
* alibi_batch_60.mp4

then, here the first one, `alibi_batch_1.mp4` will now be deleted and it'll look like this:

* `alibi_batch_2.mp4`
* `alibi_batch_3.mp4`
* `alibi_batch_4.mp4`
* ...
* `alibi_batch_61.mp4`

**Comment by Myzel394** [comment]
> thanks for explaining, so your alibi program will continue recording forever, no matter what the batch or duration size is

Exactly!

>  But some users might think your "max duration" may mean when it will completely stop recording. A timer.

Never thought about this before, but now thinking about it, this could do indeed lead to some confusion. I'll improve the wording to make sure it's clear that this is not a timer.

> Lastly, the only way to get it to stop recording is to hit the "stop" button, right? or have a program that shuts the alibi program down or shuts the OS down itself.

So far this is the only option. This is required because the final recording needs to be saved somewhere at the end if you tap on stop. That's why there's a dialog shown at the end, and this dialog can only be shown within the app itself (as far as I know). 

However, if you set up a custom batches folder location, you could force stop Alibi via another program, but then you'll also need to merge the batches files together yourself. I do plan to improve this in the far future.
