### ISSUE TITLE
Recording during phone calls?

### ISSUE THREAD

**Issue by xandro0777** [Myzel394/Alibi#92]
Would it be doable to record at least my own voice?

**Comment by Myzel394** [comment]
Okay so after some research, here's what I found out:

With the newest Android versions, it looks like it's not possible for Alibi to record anything during a phone call. The sound will instead be silenced completely. If you accept a call, this call recording your voice takes much more priority over Alibi.

Unfortunately, there seems to be a lot of ambiguity regarding recording phone calls. Some vendors apparently also apply specific rules because it's illegal to record phone calls in some countries. I couldn't find much information online, [the best (modern) resource was this StackOverflow answer](https://stackoverflow.com/a/71706300/9878135) stating:

> When the phone call starts Mic access is moved to the priority app which is the voice call itself and its handling app. Your app will no longer have access to the mic if it's an ordinary app. However if your app has an Accessibility service you can share the microphone

---


There are apparently some tricks by making Alibi an admin app, rooting your phone or installing Alibi as a system app. However, I **will not support** any of those methods, sorry.
